snd-soc-mt7620-i2s-objs := mt7620-i2s.o
snd-soc-mt7628-i2s-objs := mt7628-i2s.o

obj-$(CONFIG_SND_MT7620_SOC_I2S) += snd-soc-mt7620-i2s.o
obj-$(CONFIG_SND_MT7628_SOC_I2S) += snd-soc-mt7628-i2s.o

snd-soc-mt7620-wm8960-objs := mt7620-wm8960.o
snd-soc-mt7628-audio-objs := mt7628-audio.o

obj-$(CONFIG_SND_MT7628_SOC_AUDIO) += snd-soc-mt7628-audio.o
